### ISSUE TITLE
Why another .NET HdrHistogram ?

### ISSUE THREAD

**Issue by malat** [LeeCampbell/HdrHistogram.NET#1]
https://github.com/HdrHistogram/HdrHistogram/tree/master/src/main/csharp

**Comment by LeeCampbell** [comment]
Amazing you found this empty repo!

My current issues with the .net port of HdrHistogram are as following
- Is just a straight port of the Java code and not .NET idiomatic. I understand this is to support bring changes over as the Java code base moves forward.
- Changes from the Java code base are not ported over. The .NET code has just been left, and is over a year out of date (negating reasons in the bullet point above)
- The port is only partial complete.
- Test fail on master
- There is no need to be a binary like-for-like to Java as this is not a protocol, just a set of patterns and a very clever piece of engineering. For example: JUnit and NUnit diverged, but Protobuf implementations in different languages would need to stay in sync to be effective.
- No Nuget packaging
- Poor doco (due to the java coupling)
- The .NET code lives in the Java code base. This appears to solve no problem, but does muddy the waters.
- I did send a simple PR through the other week, and nothing has happened.

Just some issues.
This is not to say that Matt has done a poor job, however the job is not done.

This is also not to say that I will actually do anything here. I just created a GitHub Repo while playing around one day.

**Comment by malat** [comment]
Thanks for the info, since I was already using the .NET port since a wild I was wondering why, but its clearly a good idea to make that happen
